namespace GenderPayGap.WebUI.Models.Viewing.Download
{
    public class CSVDataSource
    {

        public static string CoHoApiOrUser = "Via CoHo API or manually entered by user when adding an employer to their account";
        public static string System = "Generated by the system";
        public static string CoHoApi = "Via CoHo API";
        public static string Reporting = "Entered by a user when reporting GPG data";

    }
}
