---

applications:
  - name: gpg-dev-service-app-name
    instances: 1
    memory: 256M

    buildpacks:
      - nginx_buildpack

    health-check-type: http
    health-check-http-endpoint: /_route-service-health

    env:
      APP_NAME: gpg-dev-ipdeny
      ROUTE_SERVICE_APP_NAME: gpg-dev-ipdeny
      ROUTE_SERVICE_NAME: gpg-dev-ipdeny-service
      PROTECTED_APP_NAME: gender-pay-gap-dev
      PROTECTED_APP_SPACE_NAME: gpg-dev
      DENIED_IPS: |
        deny 1.2.3.4;
