name: 'Build, Deploy (all environments)'

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

concurrency: ${{ github.workflow }}  # Prevents more than one instance of this workflow running at the same time

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
