name: 'Build, Deploy (all environments)'

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

concurrency: ${{ github.workflow }}  # Prevents more than one instance of this workflow running at the same time

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4
        
      - name: 'Install .Net (nuget) dependencies'
        run: |
          dotnet restore GenderPayGap.Core/GenderPayGap.Core.csproj
          dotnet restore GenderPayGap.Database/GenderPayGap.Database.csproj
          dotnet restore GenderPayGap.WebUI/GenderPayGap.WebUI.csproj
          dotnet restore GenderPayGap.UnitTests/GenderPayGap.WebUI.Tests/GenderPayGap.WebUI.Tests.csproj
